### PR TITLE
API project started

### PR DESCRIPTION
**Pull request by la-ry-sa**

### CODE REVIEW

**Review by dindustack — COMMENTED** [review]
1. API Endpoint Mismatch: The Fetch API call in your index.js is targeting https://api.thecatapi.com/v1/breeds instead of the instructed [https://api.github.com/users/{GITHUB_USERNAME}/repos](https://api.github.com/users/%7BGITHUB_USERNAME%7D/repos). Make sure to replace {GITHUB_USERNAME} with your actual GitHub username.

2. Variable Definitions and DOM Manipulations Missing: The code does not include the creation of projectSection and projectList variables. Additionally, the for loop for iterating over the repositories and appending them to the list is absent. This part is crucial for displaying the fetched data on your webpage.

3. HTML and Script Issues: Your HTML file has a missing closing tag for the link element in the head section. Properly closing HTML tags is essential for correct rendering and to avoid potential issues in different browsers.

**Comment by la-ry-sa** [comment]
> 1. API Endpoint Mismatch: The Fetch API call in your index.js is targeting https://api.thecatapi.com/v1/breeds instead of the instructed [https://api.github.com/users/{GITHUB_USERNAME}/repos](https://api.github.com/users/%7BGITHUB_USERNAME%7D/repos). Make sure to replace {GITHUB_USERNAME} with your actual GitHub username.
> 2. Variable Definitions and DOM Manipulations Missing: The code does not include the creation of projectSection and projectList variables. Additionally, the for loop for iterating over the repositories and appending them to the list is absent. This part is crucial for displaying the fetched data on your webpage.
> 3. HTML and Script Issues: Your HTML file has a missing closing tag for the link element in the head section. Properly closing HTML tags is essential for correct rendering and to avoid potential issues in different browsers.

This is the open API project, not the portfolio project. I appreciate the comment #3 and I will add the closing tag, but with all due respect comments 1 and 2 are not applicable to this repository.

**Comment by dindustack** [comment]
With all due respect, I reviewed the assignment with the rubric that mentors have on GitHub - which I was given at the beginning of the program, and the AI Reviewer that goes through your work made available by Code The Dream. I have reviewed the rubric for this assignment hosted on Code the Dream and your assignment lacks one thing. 

1. Put a link to your Open API project repository in the readme.md file of your Portfolio project so your reviewer can easily find/look at your Open API project from your portfolio project. You can add a link to your read me by using the following syntax: [My Open API Project](https://github.com/yourUsernameHere/yourname-open-api) Put the words you want the link to be in hard brackets [ ] and the link to the repository in parentheses ( ).

This is a learning journey for students and mentors, issues like this tend to come up and can always be resolved. Please, kindly resubmit your assignment with the updated corrections.

**Comment by la-ry-sa** [comment]
> With all due respect, I reviewed the assignment with the rubric that mentors have on GitHub - which I was given at the beginning of the program, and the AI Reviewer that goes through your work made available by Code The Dream. I have reviewed the rubric for this assignment hosted on Code the Dream and your assignment lacks one thing.
> 
> 1. Put a link to your Open API project repository in the readme.md file of your Portfolio project so your reviewer can easily find/look at your Open API project from your portfolio project. You can add a link to your read me by using the following syntax: [My Open API Project](https://github.com/yourUsernameHere/yourname-open-api) Put the words you want the link to be in hard brackets [ ] and the link to the repository in parentheses ( ).
> 
> This is a learning journey for students and mentors, issues like this tend to come up and can always be resolved. Please, kindly resubmit your assignment with the updated corrections.

The link to my open API repository is already there in the readme.md file, please see the screenshot attached. 
readme_screenshot
I have thoroughly followed the instructions while submitting the assignment.

**Comment by dindustack** [comment]
Please, kindly resubmit the assignment, and I can mark it as `Successful`

**Comment by la-ry-sa** [comment]
Done, thanks.

**Pull request merged**
